---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cfwarp-restart
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cfwarp-restart
  namespace: default
rules:
- apiGroups: [ "apps", "extensions" ]
  resources: [ "deployments", "statefulsets" ]
  resourceNames: [ "cfwarp" ]
  verbs: [ "get", "patch", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cfwarp-restart
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cfwarp-restart
subjects:
- kind: ServiceAccount
  name: cfwarp-restart
  namespace: default
