resources:
- ../../base
nameSuffix: "-blue"
images:
- name: docker.io/nlopez/media-toolbox
  newTag: "0f604a4"
- name: brainicism/bgutil-ytdlp-pot-provider
  newTag: "0.7.4"
configMapGenerator:
- name: toolbox-config
  behavior: replace
  files:
  - yt-dlp.conf
patches:
- path: patch.yaml
  target:
    kind: Deployment
    name: toolbox
