resources:
- ../../base
nameSuffix: "-blue"
images:
- name: docker.io/nlopez/media-toolbox
  newTag: "948e2f1"
- name: brainicism/bgutil-ytdlp-pot-provider
  newTag: "0.7.4"
configMapGenerator:
- name: toolbox-config
  behavior: replace
  files:
  - yt-dlp.conf
