apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox
  namespace: media
spec:
  selector:
    matchLabels:
      app: toolbox
      version: v1
  template:
    spec:
      securityContext: null
      initContainers:
        - image: docker.io/busybox
          imagePullPolicy: IfNotPresent
          name: disable-ipv6
          securityContext:
            privileged: true
          args:
          - -w
          - net.ipv6.conf.all.disable_ipv6=1
          command:
          - /bin/sysctl
      containers:
      - name: toolbox
        securityContext: null
        command: ["/bin/bash"]
        args: ["-c", "while true; do sleep 3600; done"]
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
