---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-pv-claim
  labels:
    app: tautulli
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
