---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -job1
images:
- name: docker.io/nlopez/media-toolbox
  newTag: "d60069e"
- name: brainicism/bgutil-ytdlp-pot-provider
  newTag: 0.7.4
configMapGenerator:
- behavior: replace
  files:
  - yt-dlp.conf
  name: toolbox-config
patches: []
# - path: patch.yaml
#   target:
#     kind: CronJob
#     name: toolbox-cron
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: job1
