---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-iscsi-pvc
  namespace: media
spec:
  volumeName: radarr-iscsi-pv
  resources:
    requests:
      storage: 10G
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-ssd-iscsi-pvc
  namespace: media
spec:
  volumeName: radarr-ssd-iscsi-pv
  resources:
    requests:
      storage: 10G
  accessModes:
    - ReadWriteOnce
