---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-ssd-iscsi-pvc
  namespace: media
spec:
  volumeName: radarr-ssd-iscsi-pv
  resources:
    requests:
      storage: 10G
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pv-claim
  labels:
    app: radarr
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
