namespace: media
resources:
- deployment.yaml
configMapGenerator:
- name: toolbox-config
  files:
    - yt-dlp.conf
replacements:
- source:
    kind: Deployment
    name: toolbox
    fieldPath: metadata.name
  targets:
  - select:
      kind: ServiceAccount
    fieldPaths:
    - metadata.name
    options:
      delimiter: "-"
      index: 1
