---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
- cronjob.yaml
configMapGenerator:
- name: toolbox-cron
  files:
  - yt-dlp.conf
replacements:
- source:
    name: toolbox-cron
    kind: CronJob
    fieldPath: metadata.name
  targets:
  - fieldPaths:
    - metadata.name
    options:
      delimiter: '-'
      index: 1
    select:
      kind: CronJob
