---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -green
images:
- name: docker.io/nlopez/media-toolbox
  newTag: "91861a1"
- name: brainicism/bgutil-ytdlp-pot-provider
  newTag: "0.8.3"
configMapGenerator:
- behavior: replace
  files:
  - yt-dlp.conf
  name: toolbox-config
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: green
