resources:
- ../../base
nameSuffix: "-green"
images:
- name: docker.io/nlopez/media-toolbox
  newTag: "d6ed04e"
- name: brainicism/bgutil-ytdlp-pot-provider
  newTag: "0.7.4"
configMapGenerator:
- name: toolbox-config
  behavior: replace
  files:
  - yt-dlp.conf
