resources:
- ../../base
nameSuffix: "-green"
images:
- name: docker.io/nlopez/media-toolbox
  newTag: 5ebe6a7
configMapGenerator:
- name: toolbox-config
  behavior: replace
  files:
    - yt-dlp.conf
